//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.Detail = new HashSet<Detail>();
        }
    
        public int TopicID { get; set; }
        public string TopicExplain { get; set; }
        public int TopicScore { get; set; }
        public int TopicType { get; set; }
        public string TopicA { get; set; }
        public string TopicB { get; set; }
        public string TopicC { get; set; }
        public string TopicD { get; set; }
        public int TopicSort { get; set; }
        public string TopicAnswer { get; set; }
        public int PaperID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Detail { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
